language: java
jdk:
  - oraclejdk7
before_script:
  - "./decrypt.sh"
  - "export JAVA_OPTS=-Xmx512m"
install: 
  - ./cmds/ci/install.sh
script:
  - "mvn test -B -Dit -Drepoz.gcs.bucket=repoz-test-travisci"
  - "./cmds/prod/update-ci.sh"
>>>>>>> master
env:
  - secure: "CXixpO++4Dw+zk4G3S2lG4Sl0BrldPnSg2tAuyJAsyRPd2chToYS+NBJQY7FjAQScnsrcGcs56ymnqOnWdgrcAyJSCEDeuBTF0pq1A3IiXcIYM3JY4rx4oYYncu5rNG2MUN4avcdp6IdfWOem1cvzOCThxktBKi4Jn773OdVcwo="

