language: java
jdk:
  - oraclejdk7
before_script:
  - "./decrypt.sh"
  - "export JAVA_OPTS=-Xmx512m"
install: "echo we do not need install"
script: "mvn clean install -B"
env:
  - secure: "I4sXfGqH8nmVfQ4a4jC0zqMaXj4x58i/p7sQki0E/JoLPSWdWKoR661ZnBtrd5FgMRtEwg2BvCrezwb6r5f6tJpntn0qVdAmL5GUtOJa3Qk6UW6Fcw8rQ+tIu+NMOxPdkzbTCMrZeBxZVAaTNRWUMzYngXI5b93WXqZ9HKP4YHQ="

