language: java
jdk:
  - oraclejdk7
before_script:
  - "./decrypt.sh"
  - "export JAVA_OPTS=-Xmx512m"
install: "echo we do not need install"
script: "mvn clean install -B"
env:
  - secure: "XB/Qdy+PDrAFFweCJ3D/kNM1fzy8CX3BVTli3F039kKDxFmqNsppzvrwQjpf0Cq98dwK7a6wTIbjdfJZNaeq9eAZYs7nPuj0u8c/3y+v/P/VBppUKw9ql9d5PmZ4LvbSkBvKvnHZmDu5dPf0L4fEOw8Fy3bdSKNG2YvgCVzAG+E="

